### ISSUE TITLE
cannot compute check result

### ISSUE THREAD

**Issue by theundefined** [freddy36/check_mk_extensions#5]
I try to use. I've put agent to servers (with bird 1.4 and bird 1.6 - on both i've the same problem), then i've put checks into check_mk server (1.2.6p2 version).
When i try to get data i have:
{code}
root@monit:~# check_mk -v bgp-server |grep BIRD
Check_mk version 1.2.6p2
BIRD Memory          OK - Routing tables: 21 kB, Route attributes: 9788 B, ROA tables: 192 B, Protocols: 30 kB, Total: 102 kB
BIRD Protocol bgp1   PEND - Cannot compute check result: Value overflow
BIRD Protocol bgp2   PEND - Cannot compute check result: No time difference
BIRD Protocol device1 PEND - Cannot compute check result: No time difference
BIRD Protocol direct1 PEND - Cannot compute check result: No time difference
BIRD Protocol kernel1 PEND - Cannot compute check result: No time difference
BIRD Status          OK - version 1.6.3, up since 21:57:39, last reconfiguration: 2017-06-21 13:55:07
{code}
debug doesn't show nothing more - there is no python exception.
Do you have any idea how to deal with it and get peers statistics?

**Comment by theundefined** [comment]
data from agent:
{code}
<<<bird>>>
0001 BIRD 1.6.3 ready.
1000 BIRD 1.6.3
1011 Router ID is 1.2.3.4
1011     Current server time is 2017-06-22 10:13:29
1011     Last reboot on 2017-06-21 13:55:07
1011     Last reconfiguration on 2017-06-21 13:55:07
0013 Daemon is up and running
1018 BIRD memory usage
1018     Routing tables:     21 kB
1018     Route attributes: 9788  B
1018     ROA tables:        192  B
1018     Protocols:          30 kB
1018     Total:             102 kB
2002 name     proto    table    state  since       info
1002 device1  Device   master   up     2017-06-21  
1006   Preference:     240
1006       Input filter:   ACCEPT
1006       Output filter:  REJECT
1006       Routes:         0 imported, 0 exported, 0 preferred
1006       Route change stats:     received   rejected   filtered    ignored   accepted
1006         Import updates:              0          0          0          0          0
1006         Import withdraws:            0          0        ---          0          0
1006         Export updates:              0          0          0        ---          0
1006         Export withdraws:            0        ---        ---        ---          0
1006     
1002 direct1  Direct   master   up     2017-06-21  
1006   Preference:     240
1006       Input filter:   ACCEPT
1006       Output filter:  REJECT
1006       Routes:         2 imported, 0 exported, 2 preferred
1006       Route change stats:     received   rejected   filtered    ignored   accepted
1006         Import updates:              2          0          0          0          2
1006         Import withdraws:            0          0        ---          0          0
1006         Export updates:              0          0          0        ---          0
1006         Export withdraws:            0        ---        ---        ---          0
1006     
1002 kernel1  Kernel   master   up     2017-06-21  
1006   Preference:     10
1006       Input filter:   ACCEPT
1006       Output filter:  ACCEPT
1006       Routes:         7 imported, 1 exported, 7 preferred
1006       Route change stats:     received   rejected   filtered    ignored   accepted
1006         Import updates:              7          0          0          0          7
1006         Import withdraws:            0          0        ---          0          0
1006         Export updates:             12         11          0        ---          1
1006         Export withdraws:            0        ---        ---        ---          0
1006     
1002 bgp1     BGP      master   up     2017-06-21  Established   
1006   Preference:     100
1006       Input filter:   ACCEPT
1006       Output filter:  as1234
1006       Routes:         0 imported, 1 exported, 0 preferred
1006       Route change stats:     received   rejected   filtered    ignored   accepted
1006         Import updates:              0          0          0          0          0
1006         Import withdraws:            0          0        ---          0          0
1006         Export updates:             10          0          9        ---          1
1006         Export withdraws:            0        ---        ---        ---          0
1006       BGP state:          Established
1006         Neighbor address: 1.2.3.4
1006         Neighbor AS:      3210
1006         Neighbor ID:      4.5.6.7
1006         Neighbor caps:    refresh restart-aware AS4
1006         Session:          external multihop AS4
1006         Source address:   2.3.4.5
1006         Hold timer:       45/90
1006         Keepalive timer:  17/30
1006     
1002 bgp2     BGP      master   up     2017-06-21  Established   
1006   Preference:     100
1006       Input filter:   ACCEPT
1006       Output filter:  REJECT
1006       Routes:         1 imported, 0 exported, 1 preferred
1006       Route change stats:     received   rejected   filtered    ignored   accepted
1006         Import updates:              1          0          0          0          1
1006         Import withdraws:            0          0        ---          0          0
1006         Export updates:             10          1          9        ---          0
1006         Export withdraws:            0        ---        ---        ---          0
1006       BGP state:          Established
1006         Neighbor address: 10.35.1.2
1006         Neighbor AS:      12345
1006         Neighbor ID:      1.2.3.4
1006         Neighbor caps:    refresh AS4
1006         Session:          internal AS4
1006         Source address:   10.35.1.1
1006         Hold timer:       144/180
1006         Keepalive timer:  48/60
1006     
10000 1498045767 /etc/bird/bird.conf
10000 1496158867 /etc/bird/bird.conf.orig
10000 1484125518 /etc/bird/bird.conf.ucf-dist
{code}
(ip's and as obfuscated)

**Comment by freddy36** [comment]
The current version was tested/developed with 1.2.8.
I would suggest you try the previous version:
https://mathias-kettner.de/check_mk_exchange_download.php?HTML=&file=bird-1.1.mkp
